name: CI-CD Docker Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: webapp-ci-cd
  IMAGE_TAG: 1.0.1
  DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

  # ===============================
  # JOB 1 - CI : BUILD + PUSH
  # ===============================
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: |
          docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

  # ===============================
  # JOB 2 - SECURITY : TRIVY SCAN
  # ===============================
  security_scan:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | \
          sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan Docker image with Trivy
        run: |
          trivy image \
            --exit-code 1 \
            --severity CRITICAL,HIGH \
            --no-progress \
            $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

  # ===============================
  # JOB 3 - CD : DEPLOY (CORRIGÉ)
  # ===============================
  deploy:
    needs: security_scan
    runs-on: runner-lab

    steps:
      - name: Check Docker
        run: docker --version

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull latest image
        run: |
          docker pull $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Stop existing container
        run: |
          docker stop ci-app || true

      - name: Remove old container
        run: |
          docker rm ci-app || true

      - name: Clean unused Docker resources
        run: |
          docker system prune -f

      - name: Run new container
        run: |
          docker run -d \
            -p 80:80 \
            --restart=always \
            --name ci-app \
            $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG